---
AWSTemplateFormatVersion: '2010-09-09'

Resources:

  AccessCardApp:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
      - AttributeName: subject-id
        KeyType: HASH
      - AttributeName: subject-topic
        KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: subject-id
        AttributeType: S
      - AttributeName: subject-topic
        AttributeType: S
      GlobalSecondaryIndexes: []
      BillingMode: PROVISIONED
      TableName: access-card-app
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TableAccessCardAppReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: AccessCardApp
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/access-card-app
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable

  TableAccessCardAppReadCapacityScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: TableAccessCardAppReadCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/access-card-app
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      PolicyName: access-card-app-read-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70

  TableAccessCardAppWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: AccessCardApp
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/access-card-app
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable

  TableAccessCardAppWriteCapacityScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: TableAccessCardAppReadCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/access-card-app
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      PolicyName: access-card-app-write-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70

Outputs:

  StackName:
    Description: "DynamoDB Stack Name"
    Value: !Sub ${AWS::StackName}
    Export:
      Name: !Sub "Lab3DynamoDbStackName"

  AccessCardAppTableName:
    Description: "DynamoDB AccessCardApp Name"
    Value: !Ref AccessCardApp
    Export:
      Name: !Sub "${AWS::StackName}-AccessCardAppTableName"
