---
AWSTemplateFormatVersion: "2010-09-09"

Description: "This stack creates a Secrets Manager secret for holding the SSH key required to access GitHub."

Resources:

  GitHubSecretKmsKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: "KMS Key that can be used for encrypting Secrets Manager data"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: "KmsCustomPolicyForGitHubSshKey"
        Statement:
          Sid: "IAM policies"
          Effect: "Allow"
          Principal:
            AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
          Action: "kms:*"
          Resource: "*"
      MultiRegion: false
      PendingWindowInDays: 7

  GitHubSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      Description: "Secret for storing the GitHub SSH Key"
      KmsKeyId: !Ref GitHubSecretKmsKey
      Name: "GitHubSecret"
      SecretString: "Value to be replaced"

Outputs:

  GitHubSecretArn:
    Description: "ARN for GitHubSecret"
    Value: !Ref GitHubSecret
    Export:
      Name: !Sub "${AWS::StackName}-GitHubSecretArn"

