---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template is the base template for the API Gateway basic resources. It does not include routes or integrations - 
  each route and integration will have their own stack.

# Metadata:
#   template metadata

Parameters:
  CorsTrustedDomainsParam:
    Type: String
    Description: "A CSV string with trusted domains for API calls. Example to add two sites: https://www.example.tld,http://localhost:5000"
    Default: "http://localhost,http://localhost:9000,https://internal.sandybox.com"
#   FirstTrustedInternetCider:
#     Type: String
#     Description: "CIDR of a host or network from the Internet to trust for incoming traffic to the Public VPC"
#     Default: "0.0.0.0/0"

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:

#######################################################################################################################
###                                                                                                                 ###
###                                                 API HTTP GATEWAY                                                ###
###                                                                                                                 ###
#######################################################################################################################

  PublicEventApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: 
        - "Content-Type"
        - "X-Amz-Date"
        - "Authorization"
        - "X-Api-Key"
        - "X-Amz-Security-Token"
        AllowMethods: 
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
        AllowOrigins: 
          Fn::Split:
          - ","
          - !Ref CorsTrustedDomainsParam
        ExposeHeaders: 
        - "Date"
        - "x-api-id"
        MaxAge: 86400
      Description: "A Public API Gateway"
      DisableExecuteApiEndpoint: false  # For production, this will typically be disabled/true to force clients to use the custom domain
      Name: "lab3-api"
      ProtocolType: "HTTP"
      Version: "v1"

Outputs:

  PublicEventApiGatewayId:
    Description: "PublicEventApiGateway ID"
    Value: !Ref PublicEventApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-PublicEventApiGatewayId"

  PublicEventApiGatewayEndPoint:
    Description: "PublicEventApiGateway EndPoint"
    Value: !GetAtt PublicEventApiGateway.ApiEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-PublicEventApiGatewayEndPoint"
