AWSTemplateFormatVersion: '2010-09-09'

Description: Serverless patterns - Cognito User Pool

Parameters:
  Email:
    Type: String
  CallbackUrl:
    Type: String
  PublicDnsNameParam:
    Type: String
    Description: "The domain name of the public DNS zone, for example: example.tld"

Resources:
  
  CognitoAuthorizerUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate: 
          EmailMessage: "Verification code: {####} | Temporary Password: {####}"
          EmailSubject: "Employee Account Invitation"
        UnusedAccountValidityDays: 3
      MfaConfiguration: "OFF" # Note: for real organizations, this will probably be on
      Policies:
        PasswordPolicy: 
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 1
      UserPoolName: employee-userpool
      VerificationMessageTemplate:
        DefaultEmailOption: "CONFIRM_WITH_CODE"

  CognitoAuthorizerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AllowedOAuthFlows: 
      - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: 
      - aws.cognito.signin.user.admin
      - email
      - openid
      - profile
      CallbackURLs: 
      - Fn::Sub:
        - "https://internal.${DomainName}/callback.html"
        - DomainName: !Ref PublicDnsNameParam
      - "http://localhost/callback.html"
      - "http://localhost:9000/callback.html"
      - Fn::Sub:
        - "https://internal.${DomainName}/loggedout.html"
        - DomainName: !Ref PublicDnsNameParam
      - "http://localhost/loggedout.html"
      - "http://localhost:9000/loggedout.html"
      ClientName: employee-cognito-client
      LogoutURLs:
      - Fn::Sub:
        - "https://internal.${DomainName}/loggedout.html"
        - DomainName: !Ref PublicDnsNameParam
      - "http://localhost/loggedout.html"
      - "http://localhost:9000/loggedout.html"
      SupportedIdentityProviders: 
      - COGNITO
      UserPoolId: !Ref CognitoAuthorizerUserPool

  CognitoAuthorizerUserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties: 
      UserAttributes: 
      - Name: email
        Value: !Ref Email
      Username: !Ref Email
      UserPoolId: !Ref CognitoAuthorizerUserPool

  CognitoAuthorizerUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
      Identifier: com.apigw
      Name: com.apigw
      Scopes: 
      - ScopeDescription: scope_description
        ScopeName: scope_name
      UserPoolId: !Ref CognitoAuthorizerUserPool
      
  CognitoAuthorizerUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: 
        Fn::Sub:
        - "staff-auth.${DomainName}"
        - DomainName: !Ref PublicDnsNameParam
      UserPoolId: !Ref CognitoAuthorizerUserPool

Outputs:

  HostedUi:
    Description: Hosted UI
    # Value: !Sub "https://${CognitoAuthorizerUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${CognitoAuthorizerUserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=${CallbackUrl}"
    Value: 
      Fn::Sub:
      - "https://staff-auth.${DomainName}/login?client_id=${CognitoAuthorizerUserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=${CallbackUrl}"
      - DomainName: !Ref PublicDnsNameParam
