---
AWSTemplateFormatVersion: "2010-09-09"

Description: This template is the base template for the API Gateway base configuration

# Metadata:
#   template metadata

Parameters:
  CorsTrustedDomainsParam:
    Type: String
    Description: "A CSV string with trusted domains for API calls. Example to add two sites: https://www.example.tld,http://localhost:5000"
    Default: "http://localhost,http://localhost:9000,https://internal.sandybox.link:8443,https://internal-api.sandybox.link:8443"
  CognitoStackNameParam:
    Type: String
    Description: "The stack name of the Cognito User Pool"
  CognitoIssuerUrlParam:
    Type: String
    Description: "The Issuer URL from https://cognito-idp.[region].amazonaws.com/[userPoolId]/.well-known/openid-configuration (refer to the issuer claim)"

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:

#######################################################################################################################
###                                                                                                                 ###
###                                                 API HTTP GATEWAY                                                ###
###                                                                                                                 ###
#######################################################################################################################

  InternalWebAppApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: 
        - "Content-Type"
        - "X-Amz-Date"
        - "Authorization"
        - "X-Api-Key"
        - "X-Amz-Security-Token"
        AllowMethods: 
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
        AllowOrigins: 
          Fn::Split:
          - ","
          - !Ref CorsTrustedDomainsParam
        ExposeHeaders: 
        - "Date"
        - "x-api-id"
        MaxAge: 86400
      Description: "An API Gateway for web applications"
      DisableExecuteApiEndpoint: true  # For production, this will typically be disabled/true to force clients to use the custom domain
      Name: "lab3-web-api"
      ProtocolType: "HTTP"
      Version: "v1"

  InternalWebAppApiGatewayAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties: 
      ApiId: !Ref InternalWebAppApiGateway
      AuthorizerType: "JWT"
      IdentitySource: 
      - "$request.header.Authorization"
      JwtConfiguration: 
        Audience: 
        - Fn::ImportValue: !Sub "${CognitoStackNameParam}-CognitoAlbUserPoolClientId"
        Issuer: !Ref CognitoIssuerUrlParam
      Name: "internal-auth"

Outputs:

  InternalWebAppApiGatewayId:
    Description: "InternalWebAppApiGateway ID"
    Value: !Ref InternalWebAppApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-InternalWebAppApiGatewayId"

  InternalWebAppApiGatewayEndPoint:
    Description: "InternalWebAppApiGateway EndPoint"
    Value: !GetAtt InternalWebAppApiGateway.ApiEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-InternalWebAppApiGatewayEndPoint"

  InternalWebAppApiGatewayAuthorizerId:
    Description: "InternalWebAppApiGatewayAuthorizer EndPoint"
    Value: !Ref InternalWebAppApiGatewayAuthorizer
    Export:
      Name: !Sub "${AWS::StackName}-InternalWebAppApiGatewayAuthorizerId"
