---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Define the bucket and supporting infrastructure for New Events"

# Metadata:
#   template metadata

Parameters:
  BucketNameParam:
    Type: String
    Default: "lab4-new-events-qpwoeiryt"
  InventoryBucketNameParam:
    Type: String
    Default: "lab4-new-events-inventory-qpwoeiryt"
  S3SourceBucketParam:
    Type: String
    Description: "The S3 bucket name containing the Lambda function ZIP file"

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:

#######################################################################################################################
###                                                                                                                 ###
###                                               S3 New Event Bucket                                               ###
###                                                                                                                 ###
#######################################################################################################################


  S3NewEventStoreNotificationDeadLetterQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      MessageRetentionPeriod: 86400
      QueueName: "S3NewEventStoreNotificationDeadLetterQueue"
      VisibilityTimeout: 300

  S3NewEventStoreNotificationQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      MessageRetentionPeriod: 86400
      QueueName: "S3NewEventStoreNotificationQueue"
      RedriveAllowPolicy:
        redrivePermission: "allowAll"
      RedrivePolicy:
        deadLetterTargetArn : !GetAtt S3NewEventStoreNotificationDeadLetterQueue.Arn
        maxReceiveCount : 3
      VisibilityTimeout: 300

  S3NewEventStoreNotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "S3NewEventStoreNotificationTopic"
      FifoTopic: false
      Subscription:
      - Protocol: sqs
        Endpoint: !GetAtt S3NewEventStoreNotificationQueue.Arn
      TopicName: "S3NewEventStoreNotification"

  S3NewEventStoreNotificationPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: sns:Publish
            Resource: !Ref S3NewEventStoreNotificationTopic
      Topics:
        - !Ref S3NewEventStoreNotificationTopic

  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Resource: !GetAtt S3NewEventStoreNotificationQueue.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref S3NewEventStoreNotificationTopic
      Queues:
      - Ref: S3NewEventStoreNotificationQueue

  S3NewEventStoreInventoryBucketPolicy:
    Type: AWS::S3::BucketPolicy 
    Properties: 
      Bucket: !Ref S3NewEventStoreBucket
      PolicyDocument: 
        Statement:
        - Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action:
          - s3:PutObject
          Resource:
          - !Join ["", ["arn:aws:s3:::", !Ref S3NewEventStoreBucket, "/*"]]
          Condition:
            ArnLike:
              aws:SourceArn:
              - !Join ["", ["arn:aws:s3:::", !Ref S3NewEventStoreBucket, "/*"]]
            StringEquals:
              aws:SourceAccount:
              - !Sub '${AWS::AccountId}'
              s3:x-amz-acl: bucket-owner-full-control 

  S3NewEventStoreInventoryBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      AccessControl: "Private"
      BucketName: !Ref InventoryBucketNameParam

  S3NewEventStoreBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - "S3NewEventStoreInventoryBucket"
    Properties: 
      AccessControl: "Private"
      BucketName: !Ref BucketNameParam
      LifecycleConfiguration: 
        Rules: 
        - AbortIncompleteMultipartUpload: 
            DaysAfterInitiation: 1
          ExpirationInDays: 7
          Id: !Sub "${BucketNameParam}-archive-lifecycle-01"
          Status: "Enabled"
      NotificationConfiguration: 
        TopicConfigurations: 
        - Event: "s3:ObjectCreated:*"   # See https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-event-types
          Topic: !Ref S3NewEventStoreNotificationTopic
      InventoryConfigurations: 
      - Destination: 
          BucketAccountId: !Sub '${AWS::AccountId}'
          BucketArn:
            Fn::Sub:
            - "arn:${AWS::Partition}:s3:::${TargetBucket}"
            - TargetBucket: !Ref InventoryBucketNameParam
          Format: CSV
          Prefix: "inv-"
        Enabled: true
        Id: "new-event-inventory"
        IncludedObjectVersions: Current
        OptionalFields: 
        - Size
        - LastModifiedDate
        - StorageClass
        - ETag
        - IsMultipartUploaded
        - ReplicationStatus
        - ObjectLockRetainUntilDate
        - IntelligentTieringAccessTier
        Prefix: "inv-filter-"
        ScheduleFrequency: Daily
      Tags: 
      - Key: Purpose
        Value: NewEventStore


#######################################################################################################################
###                                                                                                                 ###
###                                                 Lambda Function                                                 ###
###                                                                                                                 ###
#######################################################################################################################

  S3NewEventLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: "S3EventFunctionRoleAssumeRolePolicyDocument"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
      Description: "Lambda role for S3NewEventLambdaFunction"
      Policies:
      - PolicyName: S3NewEventLambdaFunctionPolicy01
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: arn:aws:logs:*:*:*
      - PolicyName: S3NewEventLambdaFunctionPolicy02
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: "Allow"
            Action:
            - "sqs:ReceiveMessage"
            - "sqs:DeleteMessage"
            - "sqs:GetQueueAttributes"
            - "sqs:ChangeMessageVisibility"
            Resource: !GetAtt S3NewEventStoreNotificationQueue.Arn
      - PolicyName: S3NewEventLambdaFunctionPolicy03
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: "Allow"
            Action:
            - "s3:GetBucketObjectLockConfiguration"
            - "s3:GetObjectAcl"
            - "s3:GetObject"
            - "s3:GetObjectRetention"
            - "s3:GetObjectVersionTagging"
            - "s3:GetObjectAttributes"
            - "s3:GetObjectVersionAcl"
            - "s3:GetObjectTagging"
            - "s3:GetObjectLegalHold"
            - "s3:GetObjectVersionAttributes"
            - "s3:GetObjectVersion"
            - "s3:ListBucket"
            Resource:
            - !GetAtt S3NewEventStoreInventoryBucket.Arn
            - Fn::Sub: 
              - "${BucketArn}/*"
              - BucketArn: !GetAtt S3NewEventStoreInventoryBucket.Arn
      - PolicyName: S3NewEventLambdaFunctionPolicy04
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: "Allow"
            Action:
            - "sns:Publish"
            Resource: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:*"
      RoleName: S3NewEventLambdaFunctionRole

  S3NewEventLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName:
        Fn::Sub:
        -  "/aws/lambda/${functionRef}"
        - functionRef: !Ref S3NewEventLambdaFunction
      RetentionInDays: 7

  S3NewEventLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Architectures: 
      - "arm64"
      Environment:
        Variables: 
          DEBUG: "1"
      Code: 
        S3Bucket: !Ref S3SourceBucketParam
        S3Key: "s3_new_event.zip"
      Description: "Start the GitHub Sync Server if required"
      FunctionName: "S3NewEventLambdaFunction"
      Handler: "s3_new_event.handler"
      MemorySize: 128
      Role: !GetAtt S3NewEventLambdaFunctionRole.Arn
      Runtime: "python3.8"
      Timeout: 300

  S3NewEventLambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt S3NewEventStoreNotificationQueue.Arn
      FunctionName: !GetAtt S3NewEventLambdaFunction.Arn


# Outputs:
#   set of outputs
