---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  ObjectTableNameParam:
    Type: String

  AccountTableNameParam:
    Type: String

Resources:

  ObjectTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: AccountNumber
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: "AccountNumberIdx"
        KeySchema: 
        - AttributeName: "AccountNumber"
          KeyType: HASH
        - AttributeName: "SK"
          KeyType: RANGE
        Projection: 
          ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Ref ObjectTableNameParam

  AccountTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: EventKey
        AttributeType: S
      - AttributeName: PreviousRequestIdReference
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: "EventKeyIdx"
        KeySchema: 
        - AttributeName: "EventKey"
          KeyType: HASH
        - AttributeName: "SK"
          KeyType: RANGE
        Projection: 
          ProjectionType: "ALL"
      - IndexName: "PreviousRequestIdReferenceIdx"
        KeySchema: 
        - AttributeName: "PreviousRequestIdReference"
          KeyType: HASH
        - AttributeName: "SK"
          KeyType: RANGE
        Projection: 
          ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Ref AccountTableNameParam
      

Outputs:

  ObjectTableName:
    Description: "DynamoDB ObjectTable Name"
    Value: !Ref ObjectTable
    Export:
      Name: !Sub "${AWS::StackName}-ObjectTableName"

  AccountTableName:
    Description: "DynamoDB AccountTable Name"
    Value: !Ref AccountTable
    Export:
      Name: !Sub "${AWS::StackName}-AccountTableName"
