---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template is an attempt to define all IaC services in AWS required for a basic demonstration of processing data 
  incoming via API Gateway and then through a Lambda handler the data is extracted and submitted to Kineses, which in 
  turn will do some very basic translation/conversion before persisting the data in S3. The S3 bucket will send events
  via SNS and SQS to another Lambda function intended as the final data processing operation. The incoming data up to
  the S3 bucket is about capturing the event streams and everything after the S3 bucket is about processing and 
  consuming the event data. Objects are encrypted and when relevant, AWS KMS keys are used.

# Metadata:
#   template metadata

Parameters:
  S3InventoryBucketNameParam:
    Type: String
    Description: "The name of the S3 bucket the CSV inventory of all other buckets are stored"
  S3EventBucketForProcessABCNameParam:
    Type: String
    Description: "The name of the S3 bucket where the incoming event data will be stored. This is the Event store. "

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:

  S3EventsInventoryBucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Ref S3InventoryBucketNameParam

  S3EventStoreBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      AccessControl: "Private"
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault: 
              KMSMasterKeyID: "aws/s3"
              SSEAlgorithm: "aws:kms"
      BucketName: !Ref S3EventBucketForProcessABCNameParam
      IntelligentTieringConfigurations: 
        - Id: !Sub "${S3EventBucketForProcessABCNameParam}-tiering"
          Status: "Enabled"
          Tierings: 
          - AccessTier: "ARCHIVE_ACCESS"
            Days: 7
          - AccessTier: "DEEP_ARCHIVE_ACCESS"
            Days: 14
      InventoryConfigurations: 
        - InventoryConfiguration
      LifecycleConfiguration: 
        LifecycleConfiguration
      LoggingConfiguration: 
        LoggingConfiguration
      MetricsConfigurations: 
        - MetricsConfiguration
      NotificationConfiguration: 
        NotificationConfiguration
      ObjectLockConfiguration: 
        ObjectLockConfiguration
      ObjectLockEnabled: Boolean
      OwnershipControls: 
        OwnershipControls
      PublicAccessBlockConfiguration: 
        PublicAccessBlockConfiguration
      ReplicationConfiguration: 
        ReplicationConfiguration
      Tags: 
        - Tag
      VersioningConfiguration: 
        VersioningConfiguration
      WebsiteConfiguration: 
        WebsiteConfiguration


Outputs:
  set of outputs
