---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template is an attempt to define all IaC services in AWS required for a basic demonstration of processing data 
  incoming via API Gateway and then through a Lambda handler the data is extracted and submitted to Kineses, which in 
  turn will do some very basic translation/conversion before persisting the data in S3. The S3 bucket will send events
  via SNS and SQS to another Lambda function intended as the final data processing operation. The incoming data up to
  the S3 bucket is about capturing the event streams and everything after the S3 bucket is about processing and 
  consuming the event data. Objects are encrypted and when relevant, AWS KMS keys are used.

# Metadata:
#   template metadata

Parameters:
  S3EventBucketParam:
    Type: String
    Description: "The name of the S3 bucket where the incoming event data will be stored. This is the Event store."

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:

  S3EventStoreNotificationQueue:
    Type: AWS::SQS::Queue
    Properties: 
      KmsMasterKeyId: "alias/aws/sqs"
      MessageRetentionPeriod: 86400
      QueueName: "S3EventStoreNotificationQueue"
      RedriveAllowPolicy: Json
      RedrivePolicy: Json
      SqsManagedSseEnabled: true
      VisibilityTimeout: 60


  S3EventStoreNotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "S3EventStoreNotificationTopic"
      FifoTopic: false
      KmsMasterKeyId: "alias/aws/sns"
      # Subscription: 
      #   - Subscription
      TopicName: "S3EventStoreNotification"


  S3EventStoreBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      AccessControl: "Private"
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault: 
              KMSMasterKeyID: "aws/s3"
              SSEAlgorithm: "aws:kms"
      BucketName: !Ref S3EventBucketParam
      LifecycleConfiguration: 
        Rules: 
        - AbortIncompleteMultipartUpload: 
            DaysAfterInitiation: 1
          Id: !Sub "${S3EventBucketParam}-archive-lifecycle-01"
          Status: "Enabled"
          Transitions: 
          - StorageClass: "GLACIER"
            TransitionInDays: 7
          - StorageClass: "DEEP_ARCHIVE"
            TransitionInDays: 14
      NotificationConfiguration: 
        TopicConfigurations: 
        - Event: "s3:ObjectCreated:*"   # See https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-event-types
          Topic: !Ref S3EventStoreNotificationTopic
      Tags: 
      - Key: Purpose
        Value: EventStore
      - Key: BusinessProcess
        Value: ProcessABC


Outputs:

  S3EventStoreBucketDomainName:
    Description: "Bucket DomainName"
    Value: !GetAtt S3EventStoreBucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-${S3EventStoreBucket}"
